Reuse initial apply in expintegrator
Jutho/KrylovKit.jl pull request #53
Opened 2022-03-18 01:23 UTC by emstoudenmire

At the beginning of `expintegrator`, apply is called to apply the linear map for the purpose of determining the type `T` of other variables. However, the result is not used later in the code. This PR uses the result to start building the vectors `w`, saving one call to apply while giving exactly the same results. This could lead to a significant performance increase in cases where only a few Krylov vectors are computed, such as for small time steps.

2022-03-19 23:29 UTC, Jutho requested changes
Thanks for detecting this. I'll be happy to merge, but may I suggest the following replacement instead:
```julia
    w[1] = w₀
    w[2] = mul!(similar(w₀), Au₀, one(T))
    for j in 2:p
```

2022-03-20 16:53 UTC, emstoudenmire commented
I'm happy to make that change. One question though: in changing the loop range to start at 2, the code at the bottom of that loop won't get run for the j=1 case. Is that a concern?

2022-03-20 20:35 UTC, Jutho commented
You are of course absolute right; I was clearly not very well awake when I wrote that. I will just merge the current version. Thanks again.

2022-03-20 20:57 UTC, emstoudenmire commented
Great! I just went ahead and did change that one line to be `w[2] = mul!(similar(w₀), Au₀, one(T))` as you mentioned.

2022-03-20 22:14 UTC, merged